version: '3'
services:

  backend:
    environment:
      LOG_LEVEL: "INFO"
      CONFIG_TYPE: "dev"
    build:
      dockerfile: ./docker/prod.Dockerfile
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/portfolio
